version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8090:80"
    depends_on:
     - otel-collector
 
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus

    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
      - api

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - zipkin
 
  grafana:
    image: "grafana/grafana:latest"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: always
    volumes:
      - ./:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
